apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: testapp
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: public.ecr.aws/v6z1v0s5/realestate-angular:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        # envFrom:
        # - configMapRef:
        #     name: frontend-config
        env:
          - name: MONGODB_URI
            valueFrom: 
              secretKeyRef: 
                 name: db-secret 
                 key: MONGODB_URI
   

---
apiVersion: v1
kind: Service
metadata:
  namespace: testapp
  name: frontend-svc
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - port: 80 
    targetPort: 5000
      # nodePort: 32000

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: testapp
  name: frontend-config
data:
  MONGODB_URI: mongodb://user:secretPassword@db-service/realestate


