apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-vol
  namespace: testapp
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/deq/data"
