apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: testapp
  name: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME 
          valueFrom: 
            secretKeyRef: 
              name: db-secret 
              key: ME_CONFIG_MONGODB_ADMINUSERNAME
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD 
          valueFrom: 
            secretKeyRef: 
              name: db-secret 
              key: ME_CONFIG_MONGODB_ADMINPASSWORD
        - name: ME_CONFIG_MONGODB_SERVER 
          value: db-service
          # valueFrom: 
          #   secretKeyRef: 
          #     name: db-secret 
          #     key: ME_CONFIG_MONGODB_SERVER
        # envFrom:
        # - configMapRef:
        #     name: url    

---
apiVersion: v1
kind: Service
metadata:
  namespace: testapp
  name: mongoexpress-svc
spec:
  # type: LoadBalancer
  selector:
    app: mongo-express
  ports:
  - port: 80
    targetPort: 8081
    #    nodePort: 30021

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: testapp
  name: url
data:
  mongourl: db-service


        
